version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: airbnb_db
    environment:
      POSTGRES_USER: airbnb_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: airbnb_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
