spring:
  # 1. Configuración de Datasource
  datasource:
    url: jdbc:postgresql://localhost:5433/airbnb_db # Puerto del Docker
    username: airbnb_user
    password: password123
    driver-class-name: org.postgresql.Driver

  # 2. Configuración de JPA (Hibernate)
  jpa:
    hibernate:
      # Mostrar el SQL generado para depuración:
      ddl-auto: none # NUNCA uses 'update' o 'create' en producción, solo 'none'
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 3. Configuración de Flyway (Gestor de Migraciones)
  flyway:
    enabled: true
    locations: classpath:db/migration # Directorio donde Flyway buscará los scripts
